version: "2"

services:
  dogego:
    image: dogego
    restart: always
    environment:
      - ADDR_HTTP=:3000
      - ADDR_HTTP2=:3001
      - ENABLE_JRPC=disable
      - TLS_PEM=./certs/cert.pem
      - TLS_KEY=./certs/cert.key
      - DATABASE_DSN=user:password@tcp(dbaddr)/dbname?charset=utf8&parseTime=true
      - CORS_DOMAIN=*
      - TIME_TASK_QUEUE=timetaskqueue
      - ASYNC_TASK_QUEUE=asynctaskqueue
      - OSS_END_POINT=
      - OSS_ACCESS_KEY_ID=
      - OSS_ACCESS_KEY_SECRET=
      - SESSION_SECRET=xzvfdsfsddsfsdsdsfsfdf
      - REDIS_ADDR=127.0.0.1:6379
      - REDIS_PASSWORD=
      - GIN_MODE=debug
    ports:
      - 3000:80